import json

# Example list
data = [
    {'Part Number': '0402YC104KAT2A', 'Mfr': 'KYOCERA AVX', 'Part Status': 'Active', 'Capacitance': '0.1 µF', 'Tolerance': '±10%', 'Voltage - Rated': '16V', 'Temperature Coefficient': 'X7R', 'Operating Temperature': '-55°C ~ 125°C', 'Features': '-', 'Ratings': '-', 'Applications': 'General Purpose', 'Failure Rate': '-', 'Mounting Type': 'Surface Mount, MLCC', 'Package / Case': '0402 (1005 Metric)', 'Size / Dimension': '0.039" L x 0.020" W (1.00mm x 0.50mm)', 'Height - Seated (Max)': '-', 'Thickness (Max)': '0.022" (0.55mm)', 'Lead Spacing': '-', 'Lead Style': '-'},
    {'Part Number': 'ERJ2RKF1000X', 'Mfr': 'Panasonic Electronic Components', 'Part Status': 'Active', 'Resistance': '100 Ohms', 'Tolerance': '±1%', 'Power (Watts)': '0.1W, 1/10W', 'Composition': 'Thick Film', 'Features': 'Automotive AEC-Q200', 'Temperature Coefficient': '±100ppm/°C', 'Operating Temperature': '-55°C ~ 155°C', 'Package / Case': '0402 (1005 Metric)', 'Supplier Device Package': '0402', 'Ratings': '-', 'Size / Dimension': '0.039" L x 0.020" W (1.00mm x 0.50mm)', 'Height - Seated (Max)': '0.016" (0.40mm)', 'Number of Terminations': '2', 'Failure Rate': '-'},
    {'Part Number': 'EHF-105-01-L-D', 'Mfr': 'Samtec Inc.', 'Part Status': 'Active', 'Connector Type': 'Header', 'Contact Type': 'Male Pin', 'Pitch - Mating': '0.050" (1.27mm)', 'Number of Positions': '10', 'Number of Rows': '2', 'Row Spacing - Mating': '0.050" (1.27mm)', 'Number of Positions Loaded': 'All', 'Style': 'Board to Cable/Wire', 'Shrouding': 'Shrouded - 4 Wall', 'Mounting Type': 'Through Hole', 'Termination': 'Solder', 'Fastening Type': 'Latch Lock/Eject Hooks', 'Contact Length - Mating': '0.120" (3.05mm)', 'Contact Length - Post': '0.107" (2.71mm)', 'Overall Contact Length': '0.350" (8.89mm)', 'Insulation Height': '0.325" (8.25mm)', 'Contact Shape': 'Square', 'Contact Finish - Mating': 'Gold', 'Contact Finish Thickness - Mating': '10.0µin (0.25µm)', 'Contact Finish - Post': 'Tin', 'Contact Material': 'Phosphor Bronze', 'Insulation Material': 'Liquid Crystal Polymer (LCP), Glass Filled', 'Features': 'Keying Slot', 'Operating Temperature': '-55°C ~ 125°C', 'Ingress Protection': '-', 'Material Flammability Rating': '-', 'Insulation Color': 'Black', 'Current Rating (Amps)': '1.75A', 'Voltage Rating': '-'},
    {'Part Number': '2N3906TFR', 'Mfr': 'onsemi', 'Part Status': 'Active', 'Transistor Type': 'PNP', 'Current - Collector (Ic) (Max)': '200 mA', 'Voltage - Collector Emitter Breakdown (Max)': '40 V', 'Vce Saturation (Max) @ Ib, Ic': '400mV @ 5mA, 50mA', 'Current - Collector Cutoff (Max)': '-', 'DC Current Gain (hFE) (Min) @ Ic, Vce': '100 @ 10mA, 1V', 'Power - Max': '625 mW', 'Frequency - Transition': '250MHz', 'Operating Temperature': '-55°C ~ 150°C (TJ)', 'Mounting Type': 'Through Hole', 'Package / Case': 'TO-226-3, TO-92-3 (TO-226AA) Formed Leads', 'Supplier Device Package': 'TO-92-3'},
    {'Part Number': 'TLC5971PWP', 'Mfr': 'Texas Instruments', 'Part Status': 'Active', 'Type': 'Linear', 'Topology': 'Shift Register', 'Internal Switch(s)': 'Yes', 'Number of Outputs': '12', 'Voltage - Supply (Min)': '3V', 'Voltage - Supply (Max)': '5.5V', 'Voltage - Output': '17V', 'Current - Output / Channel': '60mA', 'Frequency': '-', 'Dimming': '-', 'Applications': '-', 'Operating Temperature': '-40°C ~ 85°C (TA)', 'Mounting Type': 'Surface Mount', 'Package / Case': '20-PowerTSSOP (0.173", 4.40mm Width)', 'Supplier Device Package': '20-HTSSOP'},
    {'Part Number': 'B130LB-13-F', 'Mfr': 'Diodes Incorporated', 'Part Status': 'Active', 'Technology': 'Schottky', 'Voltage - DC Reverse (Vr) (Max)': '30 V', 'Current - Average Rectified (Io)': '2A', 'Voltage - Forward (Vf) (Max) @ If': '445 mV @ 2 A', 'Speed': 'Fast Recovery =< 500ns, > 200mA (Io)', 'Current - Reverse Leakage @ Vr': '1 mA @ 30 V', 'Capacitance @ Vr, F': '90pF @ 4V, 1MHz', 'Mounting Type': 'Surface Mount', 'Package / Case': 'DO-214AA, SMB', 'Supplier Device Package': 'SMB', 'Operating Temperature - Junction': '-55°C ~ 125°C'},
    {'Part Number': 'RMCS0402FT100R', 'Mfr': 'Stackpole Electronics Inc', 'Part Status': 'Active', 'Resistance': '100 Ohms', 'Tolerance': '±1%', 'Power (Watts)': '0.063W, 1/16W', 'Composition': 'Thick Film', 'Features': 'Anti-Sulfur', 'Temperature Coefficient': '±100ppm/°C', 'Operating Temperature': '-55°C ~ 155°C', 'Package / Case': '0402 (1005 Metric)', 'Supplier Device Package': '0402', 'Size / Dimension': '0.039" L x 0.020" W (1.00mm x 0.50mm)', 'Height - Seated (Max)': '0.016" (0.40mm)', 'Number of Terminations': '2', 'Failure Rate': '-'},
    {'Part Number': '20021611-00010T1LF', 'Mfr': 'Amphenol ICC (FCI)', 'Part Status': 'Active', 'Connector Type': 'Header', 'Contact Type': 'Male Pin', 'Pitch - Mating': '0.050" (1.27mm)', 'Number of Positions': '10', 'Number of Rows': '2', 'Row Spacing - Mating': '0.050" (1.27mm)', 'Number of Positions Loaded': 'All', 'Style': 'Board to Cable/Wire', 'Shrouding': 'Shrouded - 4 Wall', 'Mounting Type': 'Through Hole', 'Termination': 'Solder', 'Fastening Type': 'Latch Lock/Eject Hooks', 'Contact Length - Mating': '-', 'Contact Length - Post': '0.091" (2.30mm)', 'Overall Contact Length': '-', 'Insulation Height': '0.327" (8.30mm)', 'Contact Shape': 'Square', 'Contact Finish - Mating': 'Gold', 'Contact Finish Thickness - Mating': 'Flash', 'Contact Finish - Post': 'Gold', 'Contact Material': 'Copper Alloy', 'Insulation Material': 'Plastic', 'Features': 'Keying Slot', 'Operating Temperature': '-40°C ~ 105°C', 'Ingress Protection': '-', 'Material Flammability Rating': 'UL94 V-0', 'Insulation Color': 'Black', 'Current Rating (Amps)': '1A per Contact', 'Voltage Rating': '125VAC'},
    {'Part Number': '2N3906TF', 'Mfr': 'onsemi', 'Part Status': 'Active', 'Transistor Type': 'PNP', 'Current - Collector (Ic) (Max)': '200 mA', 'Voltage - Collector Emitter Breakdown (Max)': '40 V', 'Vce Saturation (Max) @ Ib, Ic': '400mV @ 5mA, 50mA', 'Current - Collector Cutoff (Max)': '-', 'DC Current Gain (hFE) (Min) @ Ic, Vce': '100 @ 10mA, 1V', 'Power - Max': '625 mW', 'Frequency - Transition': '250MHz', 'Operating Temperature': '-55°C ~ 150°C (TJ)', 'Mounting Type': 'Through Hole', 'Package / Case': 'TO-226-3, TO-92-3 (TO-226AA) Formed Leads', 'Supplier Device Package': 'TO-92-3'},
    {'Part Number': 'TLC5971PWPR', 'Mfr': 'Texas Instruments', 'Part Status': 'Active', 'Type': 'Linear', 'Topology': 'Shift Register', 'Internal Switch(s)': 'Yes', 'Number of Outputs': '12', 'Voltage - Supply (Min)': '3V', 'Voltage - Supply (Max)': '5.5V', 'Voltage - Output': '17V', 'Current - Output / Channel': '60mA', 'Frequency': '-', 'Dimming': '-', 'Applications': '-', 'Operating Temperature': '-40°C ~ 85°C (TA)', 'Mounting Type': 'Surface Mount', 'Package / Case': '20-PowerTSSOP (0.173", 4.40mm Width)', 'Supplier Device Package': '20-HTSSOP'},
    {'Part Number': 'MBRS130LT3G', 'Mfr': 'onsemi', 'Part Status': 'Active', 'Technology': 'Schottky', 'Voltage - DC Reverse (Vr) (Max)': '30 V', 'Current - Average Rectified (Io)': '2A', 'Voltage - Forward (Vf) (Max) @ If': '445 mV @ 2 A', 'Speed': 'Fast Recovery =< 500ns, > 200mA (Io)', 'Current - Reverse Leakage @ Vr': '1 mA @ 30 V', 'Capacitance @ Vr, F': '-', 'Mounting Type': 'Surface Mount', 'Package / Case': 'DO-214AA, SMB', 'Supplier Device Package': 'SMB', 'Operating Temperature - Junction': '-65°C ~ 125°C'},
    {'Part Number': 'NMC0402X7R104K16TRPF', 'Mfr': 'NIC Components Corp', 'Part Status': 'Active', 'Capacitance': '0.1 µF', 'Tolerance': '±10%', 'Voltage - Rated': '16V', 'Temperature Coefficient': 'X7R', 'Operating Temperature': '-55°C ~ 125°C', 'Features': 'Low ESL, Ultra Low ESR', 'Ratings': '-', 'Applications': 'General Purpose', 'Failure Rate': '-', 'Mounting Type': 'Surface Mount, MLCC', 'Package / Case': '0402 (1005 Metric)', 'Size / Dimension': '0.039" L x 0.020" W (1.00mm x 0.50mm)', 'Height - Seated (Max)': '-', 'Thickness (Max)': '0.024" (0.60mm)', 'Lead Spacing': '-', 'Lead Style': '-'},
    {'Part Number': '20021611-00010T4LF', 'Mfr': 'Amphenol ICC (FCI)', 'Part Status': 'Active', 'Connector Type': 'Header', 'Contact Type': 'Male Pin', 'Pitch - Mating': '0.050" (1.27mm)', 'Number of Positions': '10', 'Number of Rows': '2', 'Row Spacing - Mating': '0.050" (1.27mm)', 'Number of Positions Loaded': 'All', 'Style': 'Board to Cable/Wire', 'Shrouding': 'Shrouded - 4 Wall', 'Mounting Type': 'Through Hole', 'Termination': 'Solder', 'Fastening Type': 'Latch Lock/Eject Hooks', 'Contact Length - Mating': '-', 'Contact Length - Post': '0.091" (2.30mm)', 'Overall Contact Length': '-', 'Insulation Height': '0.327" (8.30mm)', 'Contact Shape': 'Square', 'Contact Finish - Mating': 'Gold', 'Contact Finish Thickness - Mating': '10.0µin (0.25µm)', 'Contact Finish - Post': '-', 'Contact Material': 'Copper Alloy', 'Insulation Material': 'Plastic', 'Features': 'Keying Slot', 'Operating Temperature': '-40°C ~ 105°C', 'Ingress Protection': '-', 'Material Flammability Rating': 'UL94 V-0', 'Insulation Color': 'Black', 'Current Rating (Amps)': '1A per Contact', 'Voltage Rating': '125VAC'},
    {'Part Number': 'SBRS8130LNT3G', 'Mfr': 'onsemi', 'Part Status': 'Active', 'Technology': 'Schottky', 'Voltage - DC Reverse (Vr) (Max)': '30 V', 'Current - Average Rectified (Io)': '2A', 'Voltage - Forward (Vf) (Max) @ If': '445 mV @ 2 A', 'Speed': 'Fast Recovery =< 500ns, > 200mA (Io)', 'Current - Reverse Leakage @ Vr': '1 mA @ 30 V', 'Capacitance @ Vr, F': '-', 'Grade': 'Automotive', 'Qualification': 'AEC-Q101', 'Mounting Type': 'Surface Mount', 'Package / Case': 'DO-214AA, SMB', 'Supplier Device Package': 'SMB', 'Operating Temperature - Junction': '-65°C ~ 125°C'}
]

# Write to JSON file
with open('parts.json', 'w', encoding='utf-8') as json_file:
    json.dump(data, json_file, indent=2, ensure_ascii=False)

print("parts.json has been created successfully!")
